version: '3.8'
services:
  db:
    container_name: rest-db
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    stdin_open: true
  app:
    container_name: rest-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: [sh, -c, "npx prisma db push && npx prisma db seed && npm run dev"]
    stdin_open: true
    volumes:
      - ./src:/app/src


  

  